(()=>{
'use strict';
let faceStream=null,faceModelsLoaded=false,registeredDescriptor=null,faceRegistered=false,faceBusy=false,installed=false;
const MODEL_URL='https://cdn.jsdelivr.net/npm/@vladmandic/face-api/model/';
function stopCamera(){if(faceStream){faceStream.getTracks().forEach(t=>t.stop());faceStream=null;}const v=document.getElementById('workerFaceVideo');if(v)v.srcObject=null;}
function normPhone(v){return String(v||'').replace(/\D/g,'').replace(/^91(?=\d{10}$)/,'').replace(/^0(?=\d{10}$)/,'');}
function setFaceStatus(text,type='info'){const el=document.getElementById('workerFaceStatus');if(!el)return;el.textContent=text;el.style.background=type==='ok'?'#ecfdf5':type==='err'?'#fff1f2':'#eff6ff';el.style.color=type==='ok'?'#166534':type==='err'?'#9f1239':'#1d4ed8';}
async function loadFaceModels(){if(faceModelsLoaded)return;if(typeof faceapi==='undefined')throw new Error('Face model library load नहीं हुई');setFaceStatus('Face model load हो रहा है...');await Promise.all([faceapi.nets.tinyFaceDetector.loadFromUri(MODEL_URL),faceapi.nets.faceLandmark68Net.loadFromUri(MODEL_URL),faceapi.nets.faceRecognitionNet.loadFromUri(MODEL_URL)]);faceModelsLoaded=true;}
function ensureFaceUI(){const form=document.getElementById('workerForm');if(!form)return false;let box=document.getElementById('workerFaceBox');if(box)return true;const grid=form.querySelector('.formGrid');if(!grid)return false;const oldAttendance=document.getElementById('workerAttendanceStatus')?.closest('.field');if(oldAttendance)oldAttendance.style.display='none';box=document.createElement('div');box.id='workerFaceBox';box.className='field full';box.innerHTML='<label>📷 Worker Face Registration</label><div style="padding:14px;border:1px solid #e3e9f0;border-radius:14px;background:#f8fafc"><div id="workerFaceStatus" style="padding:10px;border-radius:10px;background:#eff6ff;color:#1d4ed8;font-weight:800;margin-bottom:10px">पहले Worker details भरें, फिर Face Register करें।</div><div id="workerFaceCamera" style="display:none;position:relative;max-width:430px;aspect-ratio:4/3;background:#081827;border-radius:16px;overflow:hidden;margin:10px auto"><video id="workerFaceVideo" autoplay playsinline webkit-playsinline muted style="width:100%;height:100%;object-fit:cover;transform:scaleX(-1)"></video></div><div style="display:flex;gap:8px;flex-wrap:wrap"><button type="button" id="workerFaceStart" class="btn btn-blue">📷 Face Camera Start</button><button type="button" id="workerFaceCapture" class="btn btn-green" disabled>✅ Face Register</button><button type="button" id="workerFaceStop" class="btn btn-light" style="display:none">Stop Camera</button></div><div class="uploadHint" style="margin-top:8px">पहली बार Worker add करते समय साफ चेहरा register करें। यही face attendance में verify होगा।</div></div>';grid.appendChild(box);document.getElementById('workerFaceStart').onclick=startFaceCamera;document.getElementById('workerFaceCapture').onclick=captureAndPrepare;document.getElementById('workerFaceStop').onclick=stopFaceUI;return true;}
function stopFaceUI(){stopCamera();const c=document.getElementById('workerFaceCamera'),s=document.getElementById('workerFaceStop'),b=document.getElementById('workerFaceCapture');if(c)c.style.display='none';if(s)s.style.display='none';if(b)b.disabled=true;setFaceStatus('Camera बंद है।');}
function waitForVideo(v){return new Promise((resolve,reject)=>{const start=Date.now();const tick=()=>{if(v.readyState>=2&&v.videoWidth>0&&v.videoHeight>0)return resolve();if(Date.now()-start>10000)return reject(new Error('Camera video तैयार नहीं हुआ'));requestAnimationFrame(tick)};tick();});}
async function startFaceCamera(){if(faceBusy)return;try{faceBusy=true;await loadFaceModels();stopCamera();let constraints={video:{facingMode:{ideal:'user'},width:{ideal:640},height:{ideal:480},frameRate:{ideal:24,max:30}},audio:false};try{faceStream=await navigator.mediaDevices.getUserMedia(constraints);}catch(e){faceStream=await navigator.mediaDevices.getUserMedia({video:true,audio:false});}const v=document.getElementById('workerFaceVideo');v.srcObject=faceStream;v.setAttribute('playsinline','');v.setAttribute('webkit-playsinline','');v.muted=true;try{await v.play();}catch(e){}await waitForVideo(v);document.getElementById('workerFaceCamera').style.display='block';document.getElementById('workerFaceStop').style.display='inline-block';document.getElementById('workerFaceCapture').disabled=false;setFaceStatus('Camera तैयार है। चेहरा सामने, रोशनी में और पूरा दिखाएँ।','ok');}catch(e){setFaceStatus('Camera शुरू नहीं हुआ: '+e.message,'err');}finally{faceBusy=false;}}
async function detectOnce(v){await waitForVideo(v);return faceapi.detectAllFaces(v,new faceapi.TinyFaceDetectorOptions({inputSize:160,scoreThreshold:.45})).withFaceLandmarks().withFaceDescriptors();}
async function captureAndPrepare(){if(faceBusy)return;try{faceBusy=true;setFaceStatus('Face scan हो रहा है... चेहरा स्थिर रखें।');const v=document.getElementById('workerFaceVideo');let detections=[];for(let i=0;i<3;i++){detections=await detectOnce(v);if(detections.length===1)break;await new Promise(r=>setTimeout(r,350));}if(detections.length!==1){setFaceStatus(detections.length>1?'एक समय में केवल एक चेहरा रखें।':'चेहरा साफ, सामने और पर्याप्त रोशनी में रखें।','err');return;}const desc=Array.from(detections[0].descriptor);if(desc.length!==128||desc.some(x=>!Number.isFinite(x))){throw new Error('Face descriptor invalid');}registeredDescriptor=desc;faceRegistered=true;setFaceStatus('✅ Face capture सफल। अब नीचे Save Worker दबाएँ।','ok');document.getElementById('workerFaceCapture').disabled=true;}catch(e){faceRegistered=false;registeredDescriptor=null;setFaceStatus('Face registration failed: '+e.message,'err');}finally{faceBusy=false;}}
function currentWorkerId(){return document.getElementById('workerId')?.value||'';}
async function setupFaceState(){if(!ensureFaceUI())return;stopCamera();registeredDescriptor=null;faceRegistered=false;const id=currentWorkerId();if(id){const r=await sb.from('workers').select('id,face_registered,face_descriptor').eq('id',id).maybeSingle();if(!r.error&&r.data?.face_registered&&Array.isArray(r.data.face_descriptor)&&r.data.face_descriptor.length===128){faceRegistered=true;registeredDescriptor=r.data.face_descriptor;setFaceStatus('🔐 इस Worker का Face पहले से registered है। चाहें तो नया face register कर सकते हैं।','ok');return;}}setFaceStatus('⚠️ Face अभी registered नहीं है। पहले Face Register करें।');}
async function saveWorkerWithFace(e){if(e){e.preventDefault();e.stopImmediatePropagation();}const id=currentWorkerId();const name=document.getElementById('workerName')?.value.trim()||'';const role=document.getElementById('workerRole')?.value.trim()||'';const phoneInput=document.getElementById('workerMobile');const phoneRaw=phoneInput?.value.trim()||'';const wage=Number(document.getElementById('workerWage')?.value||0);const village=document.getElementById('workerVillage')?.value.trim()||'';if(!name)return toast('❌ Worker name जरूरी है');if(normPhone(phoneRaw).length!==10)return toast('❌ सही 10 अंकों का mobile number डालें');if(!id&&!faceRegistered)return toast('❌ नया Worker save करने से पहले Face Register करें');const base={name,work_role:role,phone:phoneRaw,daily_rate:wage,village};let workerId=id;if(id){const payload={...base};if(faceRegistered){payload.face_descriptor=registeredDescriptor;payload.face_registered=true;payload.face_registered_at=new Date().toISOString();}const result=await sb.from('workers').update(payload).eq('id',id).select('id').single();if(result.error)return toast('❌ Worker update नहीं हुआ: '+result.error.message);workerId=result.data.id;}else{const result=await sb.from('workers').insert({...base,face_descriptor:registeredDescriptor,face_registered:true,face_registered_at:new Date().toISOString()}).select('id').single();if(result.error)return toast('❌ Worker save नहीं हुआ: '+result.error.message);workerId=result.data.id;}if(faceRegistered&&workerId){const rr=await sb.from('worker_face_registrations').upsert({worker_id:workerId,face_descriptor:registeredDescriptor,registered_at:new Date().toISOString()},{onConflict:'worker_id'});if(rr.error)return toast('⚠️ Worker save हो गया लेकिन Face registration record save नहीं हुआ: '+rr.error.message);}stopCamera();closeModal('workerModal');toast(id?'✅ Worker updated':'✅ Worker added + Face registered');if(typeof loadAll==='function')await loadAll();}
async function loadWorkerAttendanceHistory(){try{const {data,error}=await sb.from('worker_attendance').select('*').order('attendance_date',{ascending:false}).order('check_in',{ascending:false});if(error){console.warn('Attendance history:',error);return;}const by={};(data||[]).forEach(a=>{const id=a.worker_id||a.workerId;if(!id)return;(by[id]??=[]).push(a);});document.querySelectorAll('#workersList .workerCard').forEach((card,index)=>{const w=workers[index];if(!w)return;let panel=card.querySelector('.workerAttendanceHistory');if(!panel){panel=document.createElement('div');panel.className='workerAttendanceHistory';panel.style.cssText='margin-top:18px;border:1px solid #e3e9f0;border-radius:16px;background:#f8fafc;padding:14px;';card.querySelector('.workerInfo')?.appendChild(panel);}const rows=(by[w.id]||[]);const html=rows.length?rows.map(a=>{const date=String(a.attendance_date||a.date||a.work_date||a.day||'').slice(0,10)||'—';const st=String(a.status||'').toLowerCase();const ok=['present','p','yes','1','full day','half day'].includes(st);const tm=a.check_in?new Date(a.check_in).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'}):'';return `<div style="display:flex;justify-content:space-between;gap:10px;padding:8px 0;border-bottom:1px solid #e8edf2;font-size:13px"><strong>📅 ${date}</strong><span style="font-weight:800;color:${ok?'#15803d':'#dc2626'}">${ok?'✅ Present':'❌ '+(a.status||'Absent')}${tm?' • '+tm:''}</span></div>`;}).join(''):`<div style="color:#60738a;font-size:13px;padding:6px 0">अभी कोई attendance record नहीं है।</div>`;panel.innerHTML=`<div style="font-weight:900;margin-bottom:5px">📅 Date-wise Attendance</div><div style="font-size:12px;color:#60738a;margin-bottom:8px">कुल ${rows.filter(a=>['present','p','yes','1','full day','half day'].includes(String(a.status||'').toLowerCase())).length} Present</div>${html}`;});}catch(e){console.warn('Attendance history failed',e);}}
function installAttendancePanel(){const list=document.getElementById('workersList');if(!list)return;const styleId='workerAttendanceHistoryStyle';if(!document.getElementById(styleId)){const s=document.createElement('style');s.id=styleId;s.textContent='.workerAttendanceHistory{max-height:260px;overflow:auto}.workerAttendanceHistory>div:last-child{border-bottom:0!important}';document.head.appendChild(s);}loadWorkerAttendanceHistory();if(!list.dataset.attendanceObserver){list.dataset.attendanceObserver='1';const obs=new MutationObserver(()=>{clearTimeout(window.__waTimer);window.__waTimer=setTimeout(loadWorkerAttendanceHistory,120);});obs.observe(list,{childList:true,subtree:true});}}
function install(){if(installed)return;if(typeof faceapi==='undefined')return;if(typeof sb==='undefined')return;installed=true;ensureFaceUI();const originalOpen=window.openWorkerModal;if(typeof originalOpen==='function'){window.openWorkerModal=function(id=''){originalOpen(id);setTimeout(setupFaceState,120);setTimeout(installAttendancePanel,250);};}const form=document.getElementById('workerForm');if(form)form.addEventListener('submit',saveWorkerWithFace,true);installAttendancePanel();window.addEventListener('beforeunload',stopCamera);}
function boot(){install();if(!installed)setTimeout(install,700);if(!installed)setTimeout(install,1800);if(!installed)setTimeout(install,3000);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();

/* =========================================================
   WORKER PAYMENTS / BALANCE / UPI / RECEIPTS
   Admin dashboard enhancement
========================================================= */
(()=>{
'use strict';
const URL='https://iefxfyjmyssuiuyncfqz.supabase.co';
const KEY='sb_publishable_45zaRM5LLByFABddU5hm9g_4UwfnT7t';
const db=window.supabase.createClient(URL,KEY);
const esc2=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money2=v=>'₹'+Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2});
const num2=v=>{const n=Number(String(v??'').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0;};
function attendanceUnits(rows){return (rows||[]).reduce((s,a)=>{const st=String(a.status||'').trim().toLowerCase();if(['present','p','yes','1','full day','full_day'].includes(st))return s+1;if(['half','half day','half_day','halfday'].includes(st))return s+.5;return s;},0);}
function upiLink(worker,amount){const pa=String(worker.upi_id||'').trim();if(!pa||amount<=0)return '';const pn=encodeURIComponent(worker.name||'Worker');return `upi://pay?pa=${encodeURIComponent(pa)}&pn=${pn}&am=${encodeURIComponent(Number(amount).toFixed(2))}&cu=INR`;}
async function resizeReceipt(file){if(!file)return null;if(!file.type.startsWith('image/'))throw new Error('केवल image receipt चुनें');const src=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(new Error('Receipt read failed'));r.readAsDataURL(file);});const img=await new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=()=>rej(new Error('Receipt image load failed'));i.src=src;});const scale=Math.min(1,1200/img.width,1200/img.height);const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.72);}
function ensurePaymentModal(){if(document.getElementById('workerPaymentModal'))return;const m=document.createElement('div');m.id='workerPaymentModal';m.className='modal';m.innerHTML=`<div class="modalBox" style="max-width:720px"><div class="modalHead"><h3>💰 Worker Payment</h3><button class="close" type="button" id="closeWorkerPayment">×</button></div><div id="workerPaymentSummary"></div><form id="workerPaymentForm"><input type="hidden" id="wpWorkerId"><input type="hidden" id="wpPaymentId"><div class="formGrid"><div class="field"><label>Payment Amount</label><input id="wpAmount" type="number" min="1" step="0.01" required></div><div class="field"><label>Payment Date</label><input id="wpDate" type="date" required></div><div class="field"><label>Payment Method</label><select id="wpMethod"><option>UPI</option><option>Cash</option><option>Bank Transfer</option><option>Other</option></select></div><div class="field"><label>Reference / UTR</label><input id="wpRef" placeholder="UPI UTR / reference no."></div><div class="field full"><label>Receipt / Payment Screenshot</label><input id="wpReceipt" type="file" accept="image/*"><div class="uploadHint">भुगतान के बाद receipt/screenshot यहाँ लगाएँ। यह Worker की payment history में सुरक्षित रहेगा।</div><img id="wpReceiptPreview" class="photoPreview" style="display:none;max-height:240px"></div><div class="field full"><label>Notes</label><textarea id="wpNotes" placeholder="Payment के बारे में note"></textarea></div></div><div class="modalActions"><button class="btn btn-light" type="button" id="wpCancel">Cancel</button><button class="btn btn-green" type="submit">💾 Payment Save करें</button></div></form></div>`;document.body.appendChild(m);document.getElementById('closeWorkerPayment').onclick=()=>m.classList.remove('show');document.getElementById('wpCancel').onclick=()=>m.classList.remove('show');m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('show')});document.getElementById('wpReceipt').addEventListener('change',e=>{const f=e.target.files[0],img=document.getElementById('wpReceiptPreview');if(!f){img.style.display='none';return;}const r=new FileReader();r.onload=()=>{img.src=r.result;img.style.display='block'};r.readAsDataURL(f)});document.getElementById('workerPaymentForm').addEventListener('submit',saveWorkerPayment);}
async function getWorkerData(id){const [wr,ar,pr]=await Promise.all([db.from('workers').select('*').eq('id',id).maybeSingle(),db.from('worker_attendance').select('*').eq('worker_id',id).order('attendance_date',{ascending:false}),db.from('worker_payments').select('*').eq('worker_id',id).order('payment_date',{ascending:false})]);if(wr.error)throw wr.error;if(ar.error)throw ar.error;if(pr.error)throw pr.error;return {worker:wr.data,attendance:ar.data||[],payments:pr.data||[]};}
function paymentStats(data){const days=attendanceUnits(data.attendance);const earned=days*num2(data.worker.daily_rate);const paid=data.payments.reduce((s,p)=>s+num2(p.amount),0);return {days,earned,paid,pending:Math.max(0,earned-paid)};}
function receiptHTML(p){return p.receipt_url?`<a href="${esc2(p.receipt_url)}" target="_blank" rel="noopener"><img src="${esc2(p.receipt_url)}" style="width:70px;height:54px;object-fit:cover;border-radius:8px;border:1px solid #e3e9f0" alt="Receipt"></a>`:'—';}
async function openWorkerPayments(id){ensurePaymentModal();try{const data=await getWorkerData(id);if(!data.worker)return;const st=paymentStats(data);document.getElementById('wpWorkerId').value=id;document.getElementById('wpPaymentId').value='';document.getElementById('wpAmount').value=st.pending>0?Number(st.pending.toFixed(2)):'';document.getElementById('wpDate').value=new Date().toISOString().slice(0,10);document.getElementById('wpMethod').value=data.worker.upi_id?'UPI':'Cash';document.getElementById('wpRef').value='';document.getElementById('wpNotes').value='';document.getElementById('wpReceipt').value='';document.getElementById('wpReceiptPreview').style.display='none';const upi=upiLink(data.worker,st.pending);document.getElementById('workerPaymentSummary').innerHTML=`<div style="display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:18px"><div class="money"><span>कमाई</span><strong>${money2(st.earned)}</strong><small>${st.days} दिन</small></div><div class="money received"><span>दिया गया</span><strong class="green">${money2(st.paid)}</strong></div><div class="money pending"><span>बाकी</span><strong class="red">${money2(st.pending)}</strong></div></div><div style="padding:13px;border-radius:13px;background:#f8fafc;margin-bottom:16px"><b>👷 ${esc2(data.worker.name)}</b><div style="color:#60738a;margin-top:5px">Daily Wage: ${money2(data.worker.daily_rate)} ${data.worker.upi_id?'• UPI: '+esc2(data.worker.upi_id):'• UPI ID अभी सेट नहीं है'}</div>${upi?`<a class="btn btn-green" style="display:inline-block;margin-top:10px;text-decoration:none" href="${esc2(upi)}">📲 UPI से ₹${Number(st.pending).toLocaleString('en-IN')} भुगतान करें</a>`:''}</div><div style="font-weight:900;margin-bottom:8px">Payment History</div><div style="max-height:220px;overflow:auto">${data.payments.length?data.payments.map(p=>`<div style="display:grid;grid-template-columns:1fr auto auto;gap:10px;align-items:center;padding:9px 0;border-bottom:1px solid #edf1f4;font-size:13px"><span><b>${esc2(p.payment_date||'—')}</b><br>${esc2(p.payment_method||'—')} ${p.reference_no?'• '+esc2(p.reference_no):''}</span><strong class="green">${money2(p.amount)}</strong>${receiptHTML(p)}</div>`).join(''):'<div style="color:#60738a">अभी कोई payment नहीं है।</div>'}</div>`;document.getElementById('workerPaymentModal').classList.add('show');}catch(e){console.error(e);if(typeof toast==='function')toast('❌ Worker payment details नहीं मिली: '+e.message);}}
async function saveWorkerPayment(e){e.preventDefault();const id=document.getElementById('wpWorkerId').value;const paymentId=document.getElementById('wpPaymentId').value;const amount=num2(document.getElementById('wpAmount').value);if(!id||amount<=0)return;if(!paymentId){const data=await getWorkerData(id);const st=paymentStats(data);if(amount>st.pending&&st.pending>0&&!confirm(`बाकी ${money2(st.pending)} है, लेकिन आप ${money2(amount)} दर्ज कर रहे हैं। फिर भी save करें?`))return;}let receipt=null;const f=document.getElementById('wpReceipt').files[0];if(f){try{receipt=await resizeReceipt(f)}catch(err){return toast('❌ Receipt save नहीं हुई: '+err.message)}}else if(paymentId){receipt=null;}const payload={worker_id:id,amount,payment_date:document.getElementById('wpDate').value,payment_method:document.getElementById('wpMethod').value,reference_no:document.getElementById('wpRef').value.trim()||null,notes:document.getElementById('wpNotes').value.trim()||null};if(receipt)payload.receipt_url=receipt;let r;if(paymentId)r=await db.from('worker_payments').update(payload).eq('id',paymentId);else r=await db.from('worker_payments').insert(payload);if(r.error)return toast('❌ Worker payment save नहीं हुई: '+r.error.message);document.getElementById('workerPaymentModal').classList.remove('show');toast(paymentId?'✅ Worker payment updated':'✅ Worker payment saved');await renderEnhancedWorkers();}
async function setWorkerUpi(id){const {data,error}=await db.from('workers').select('id,name,upi_id').eq('id',id).maybeSingle();if(error)return toast('❌ Worker नहीं मिला: '+error.message);const val=prompt(`UPI ID डालें (${data?.name||'Worker'})`,data?.upi_id||'');if(val===null)return;const upi=val.trim();const r=await db.from('workers').update({upi_id:upi||null}).eq('id',id);if(r.error)return toast('❌ UPI ID save नहीं हुई: '+r.error.message);toast(upi?'✅ UPI ID save हो गई':'✅ UPI ID हटा दी गई');await renderEnhancedWorkers();}
async function renderEnhancedWorkers(){const box=document.getElementById('workersList');if(!box)return;const {data,error}=await db.from('workers').select('*').order('created_at',{ascending:false});if(error){console.warn('worker enhanced load',error);return;}if(!data?.length){box.innerHTML='<div class="empty">कोई Worker नहीं मिला।</div>';return;}const cards=[];for(const w of data){let a=[],p=[];try{const rr=await Promise.all([db.from('worker_attendance').select('*').eq('worker_id',w.id),db.from('worker_payments').select('*').eq('worker_id',w.id).order('payment_date',{ascending:false})]);a=rr[0].data||[];p=rr[1].data||[];}catch{}const days=attendanceUnits(a),earned=days*num2(w.daily_rate),paid=p.reduce((s,x)=>s+num2(x.amount),0),pending=Math.max(0,earned-paid);const upi=upiLink(w,pending);cards.push(`<div class="workerCard"><div class="workerHead"><div class="avatar">${esc2((w.name||'W').charAt(0).toUpperCase())}</div><div><h3>${esc2(w.name||'Worker')}</h3><p>${esc2(w.work_role||'—')}</p></div></div><div class="workerInfo"><div class="workerRow"><span>Mobile</span><strong>${esc2(w.phone||'—')}</strong></div><div class="workerRow"><span>Daily Wage</span><strong>${money2(w.daily_rate)}</strong></div><div class="workerRow"><span>काम किए दिन</span><strong>${days}</strong></div><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:14px"><div class="money"><span>कुल कमाई</span><strong>${money2(earned)}</strong></div><div class="money received"><span>दिया</span><strong class="green">${money2(paid)}</strong></div><div class="money pending"><span>बाकी</span><strong class="red">${money2(pending)}</strong></div></div><div class="actions" style="margin-top:15px"><button class="btn btn-green btn-sm" onclick="window.openWorkerPayments('${esc2(w.id)}')">💰 Payment</button><button class="btn btn-blue btn-sm" onclick="window.setWorkerUpi('${esc2(w.id)}')">📲 UPI ID</button><button class="btn btn-blue btn-sm" onclick="editWorker('${esc2(w.id)}')">✏️ Edit</button><button class="btn btn-red btn-sm" onclick="deleteWorker('${esc2(w.id)}')">🗑️ Delete</button></div>${pending>0&&upi?`<a class="btn btn-green" style="display:block;text-align:center;text-decoration:none;margin-top:10px" href="${esc2(upi)}">📲 ₹${Number(pending).toLocaleString('en-IN')} बाकी — UPI App खोलें</a>`:pending>0?`<div style="margin-top:10px;padding:10px;border-radius:11px;background:#fff7ed;color:#9a3412;font-size:12px;font-weight:800">⚠️ ${money2(pending)} बाकी • पहले UPI ID सेट करें</div>`:''}<div style="margin-top:12px;font-size:12px;color:#60738a">📄 Payment receipts: ${p.filter(x=>x.receipt_url).length}</div>${p.filter(x=>x.receipt_url).slice(0,3).map(x=>`<a href="${esc2(x.receipt_url)}" target="_blank" rel="noopener" style="display:inline-block;margin:7px 7px 0 0"><img src="${esc2(x.receipt_url)}" style="width:72px;height:52px;object-fit:cover;border-radius:8px;border:1px solid #e3e9f0" alt="Receipt"></a>`).join('')}</div></div>`);}box.innerHTML=cards.join('');}
function bootPayments(){if(!document.getElementById('workersList'))return;ensurePaymentModal();window.openWorkerPayments=openWorkerPayments;window.setWorkerUpi=setWorkerUpi;setTimeout(renderEnhancedWorkers,250);const nav=document.querySelectorAll('.nav button');nav.forEach(b=>b.addEventListener('click',()=>setTimeout(renderEnhancedWorkers,250)));}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bootPayments);else bootPayments();
})();