(()=>{
'use strict';
let faceStream=null,faceModelsLoaded=false,registeredDescriptor=null,faceRegistered=false,faceBusy=false,installed=false;
const MODEL_URL='https://cdn.jsdelivr.net/npm/@vladmandic/face-api/model/';
function stopCamera(){if(faceStream){faceStream.getTracks().forEach(t=>t.stop());faceStream=null;}const v=document.getElementById('workerFaceVideo');if(v)v.srcObject=null;}
function normPhone(v){return String(v||'').replace(/\D/g,'').replace(/^91(?=\d{10}$)/,'').replace(/^0(?=\d{10}$)/,'');}
function setFaceStatus(text,type='info'){const el=document.getElementById('workerFaceStatus');if(!el)return;el.textContent=text;el.style.background=type==='ok'?'#ecfdf5':type==='err'?'#fff1f2':'#eff6ff';el.style.color=type==='ok'?'#166534':type==='err'?'#9f1239':'#1d4ed8';}
async function loadFaceModels(){if(faceModelsLoaded)return;if(typeof faceapi==='undefined')throw new Error('Face model library load नहीं हुई');setFaceStatus('Face model load हो रहा है...');await faceapi.nets.tinyFaceDetector.loadFromUri(MODEL_URL);await faceapi.nets.faceLandmark68Net.loadFromUri(MODEL_URL);await faceapi.nets.faceRecognitionNet.loadFromUri(MODEL_URL);faceModelsLoaded=true;}
function ensureFaceUI(){const form=document.getElementById('workerForm');if(!form)return false;let box=document.getElementById('workerFaceBox');if(box)return true;const grid=form.querySelector('.formGrid');if(!grid)return false;box=document.createElement('div');box.id='workerFaceBox';box.className='field full';box.innerHTML='<label>📷 Worker Face Registration</label><div style="padding:14px;border:1px solid #e3e9f0;border-radius:14px;background:#f8fafc"><div id="workerFaceStatus" style="padding:10px;border-radius:10px;background:#eff6ff;color:#1d4ed8;font-weight:800;margin-bottom:10px">पहले Worker details भरें, फिर Face Register करें।</div><div id="workerFaceCamera" style="display:none;position:relative;max-width:430px;aspect-ratio:4/3;background:#081827;border-radius:16px;overflow:hidden;margin:10px auto"><video id="workerFaceVideo" autoplay playsinline muted style="width:100%;height:100%;object-fit:cover;transform:scaleX(-1)"></video></div><div style="display:flex;gap:8px;flex-wrap:wrap"><button type="button" id="workerFaceStart" class="btn btn-blue">📷 Face Camera Start</button><button type="button" id="workerFaceCapture" class="btn btn-green" disabled>✅ Face Register</button><button type="button" id="workerFaceStop" class="btn btn-light" style="display:none">Stop Camera</button></div><div class="uploadHint" style="margin-top:8px">पहली बार Worker add करते समय साफ चेहरा register करें। यही face attendance में verify होगा।</div></div>';grid.appendChild(box);document.getElementById('workerFaceStart').onclick=startFaceCamera;document.getElementById('workerFaceCapture').onclick=captureAndPrepare;document.getElementById('workerFaceStop').onclick=stopFaceUI;return true;}
function stopFaceUI(){stopCamera();const c=document.getElementById('workerFaceCamera'),s=document.getElementById('workerFaceStop'),b=document.getElementById('workerFaceCapture');if(c)c.style.display='none';if(s)s.style.display='none';if(b)b.disabled=true;setFaceStatus('Camera बंद है।');}
async function startFaceCamera(){if(faceBusy)return;try{faceBusy=true;await loadFaceModels();stopCamera();faceStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false});const v=document.getElementById('workerFaceVideo');v.srcObject=faceStream;document.getElementById('workerFaceCamera').style.display='block';document.getElementById('workerFaceStop').style.display='inline-block';document.getElementById('workerFaceCapture').disabled=false;setFaceStatus('Camera तैयार है। चेहरा सामने और साफ रखें।','ok');}catch(e){setFaceStatus('Camera शुरू नहीं हुआ: '+e.message,'err');}finally{faceBusy=false;}}
async function captureAndPrepare(){if(faceBusy)return;try{faceBusy=true;setFaceStatus('Face scan हो रहा है...');const v=document.getElementById('workerFaceVideo');const detections=await faceapi.detectAllFaces(v,new faceapi.TinyFaceDetectorOptions({inputSize:320,scoreThreshold:.55})).withFaceLandmarks().withFaceDescriptors();if(detections.length!==1){setFaceStatus(detections.length>1?'एक समय में केवल एक चेहरा रखें।':'चेहरा साफ और camera के सामने रखें।','err');return;}registeredDescriptor=Array.from(detections[0].descriptor);if(registeredDescriptor.length!==128)throw new Error('Face descriptor invalid');faceRegistered=true;setFaceStatus('✅ Face capture सफल। अब Save Worker दबाएँ।','ok');document.getElementById('workerFaceCapture').disabled=true;}catch(e){faceRegistered=false;registeredDescriptor=null;setFaceStatus('Face registration failed: '+e.message,'err');}finally{faceBusy=false;}}
function currentWorkerId(){return document.getElementById('workerId')?.value||'';}
async function setupFaceState(){if(!ensureFaceUI())return;stopCamera();registeredDescriptor=null;faceRegistered=false;const id=currentWorkerId();if(id){const r=await sb.from('workers').select('id,face_registered,face_descriptor').eq('id',id).maybeSingle();if(!r.error&&r.data?.face_registered&&Array.isArray(r.data.face_descriptor)&&r.data.face_descriptor.length===128){faceRegistered=true;registeredDescriptor=r.data.face_descriptor;setFaceStatus('🔐 इस Worker का Face पहले से registered है। चाहें तो नया face register कर सकते हैं।','ok');return;}}setFaceStatus('⚠️ Face अभी registered नहीं है। पहले Face Register करें।');}
async function saveWorkerWithFace(e){if(e){e.preventDefault();e.stopImmediatePropagation();}const id=currentWorkerId();const name=document.getElementById('workerName')?.value.trim()||'';const role=document.getElementById('workerRole')?.value.trim()||'';const phoneInput=document.getElementById('workerMobile');const phoneRaw=phoneInput?.value.trim()||'';const wage=Number(document.getElementById('workerWage')?.value||0);const village=document.getElementById('workerVillage')?.value.trim()||'';if(!name)return toast('❌ Worker name जरूरी है');if(normPhone(phoneRaw).length!==10)return toast('❌ सही 10 अंकों का mobile number डालें');if(!id&&!faceRegistered)return toast('❌ नया Worker save करने से पहले Face Register करें');
 const base={name,work_role:role,phone:phoneRaw,daily_rate:wage,village};
 // For an existing worker, NEVER replace phone/name/etc just because the face module ran.
 // Face-only update is used unless the normal edit form explicitly changes details.
 let workerId=id;
 if(id){const result=await sb.from('workers').update({...base,face_descriptor:faceRegistered?registeredDescriptor:undefined,face_registered:faceRegistered||undefined,face_registered_at:faceRegistered?new Date().toISOString():undefined}).eq('id',id).select('id').single();if(result.error)return toast('❌ Worker update नहीं हुआ: '+result.error.message);workerId=result.data.id;}else{const result=await sb.from('workers').insert({...base,face_descriptor:registeredDescriptor,face_registered:true,face_registered_at:new Date().toISOString()}).select('id').single();if(result.error)return toast('❌ Worker save नहीं हुआ: '+result.error.message);workerId=result.data.id;}
 if(faceRegistered&&workerId){const rr=await sb.from('worker_face_registrations').upsert({worker_id:workerId,face_descriptor:registeredDescriptor,registered_at:new Date().toISOString()},{onConflict:'worker_id'});if(rr.error)return toast('⚠️ Worker save हो गया लेकिन Face registration record save नहीं हुआ: '+rr.error.message);}
 stopCamera();closeModal('workerModal');toast(id?'✅ Worker updated':'✅ Worker added + Face registered');if(typeof loadAll==='function')await loadAll();}
function install(){if(installed)return;if(typeof faceapi==='undefined')return;if(typeof sb==='undefined')return;installed=true;ensureFaceUI();const originalOpen=window.openWorkerModal;if(typeof originalOpen==='function'){window.openWorkerModal=function(id=''){originalOpen(id);setTimeout(setupFaceState,120);};}const form=document.getElementById('workerForm');if(form)form.addEventListener('submit',saveWorkerWithFace,true);window.addEventListener('beforeunload',stopCamera);}
function boot(){install();if(!installed)setTimeout(install,700);if(!installed)setTimeout(install,1800);if(!installed)setTimeout(install,3000);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();