/* BALAJI Construction — face photo bridge only. No Worker Add/Save/Face/Attendance UI changes. */
(()=>{
  'use strict';
  let pendingPhoto=null,pendingId='',pendingName='',pendingPhone='',wrapped=false;
  const S=()=>{try{return typeof sb!=='undefined'?sb:(window.sb||null)}catch(e){return window.sb||null}};
  const snap=()=>{const v=document.getElementById('workerFaceVideo');if(!v||!v.videoWidth||!v.videoHeight)return null;const c=document.createElement('canvas'),scale=Math.min(1,640/v.videoWidth);c.width=Math.round(v.videoWidth*scale);c.height=Math.round(v.videoHeight*scale);const x=c.getContext('2d');x.translate(c.width,0);x.scale(-1,1);x.drawImage(v,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.78)};
  document.addEventListener('click',e=>{if(e.target?.id==='workerFaceCapture'){const p=snap();if(p){pendingPhoto=p;pendingId=document.getElementById('workerId')?.value||'';pendingName=document.getElementById('workerName')?.value?.trim()||'';pendingPhone=(document.getElementById('workerMobile')?.value||'').replace(/\D/g,'')}}},true);
  async function save(){if(!pendingPhoto)return;const s=S();if(!s)return;try{let w=null;if(pendingId){w=(await s.from('workers').select('id').eq('id',pendingId).maybeSingle()).data}else if(pendingPhone){w=(await s.from('workers').select('id').eq('phone',pendingPhone).order('created_at',{ascending:false}).limit(1).maybeSingle()).data}else if(pendingName){w=(await s.from('workers').select('id').eq('name',pendingName).order('created_at',{ascending:false}).limit(1).maybeSingle()).data}if(!w?.id)return;const old=(await s.from('worker_face_registrations').select('face_descriptor').eq('worker_id',w.id).maybeSingle()).data;const payload={worker_id:w.id,face_descriptor:old?.face_descriptor||null,photo_url:pendingPhoto,registered_at:new Date().toISOString(),updated_at:new Date().toISOString()};const r=await s.from('worker_face_registrations').upsert(payload,{onConflict:'worker_id'});if(r.error)console.warn('worker avatar save',r.error);pendingPhoto=null;pendingId='';pendingName='';pendingPhone='';}catch(e){console.warn('worker avatar bridge',e)}}
  function wrap(){if(wrapped||typeof window.loadAll!=='function')return;const old=window.loadAll;const f=async function(){const r=await old.apply(this,arguments);await save();return r};f.__workerAvatarWrapped=true;window.loadAll=f;wrapped=true}
  const t=setInterval(()=>{wrap();if(wrapped)clearInterval(t)},300);setTimeout(()=>clearInterval(t),15000);
})();
